version: "2"

services:
  swarm-token:
    build: .
    image: swarm-token
    environment:
      WORKER_KEY: $WORKER_KEY
      MANAGER_KEY: $MANAGER_KEY
    ports:
      - 8888:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

